name: NodeJS
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        name: checkout code

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install packages
        run: npm install

      - name: execute tests
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: success() || failure()
